### ISSUE TITLE
linking stylesheet

### ISSUE THREAD

**Issue by Rodrigap** [willzangina/prj-rev-bwfs-tea-cozy#1]
https://github.com/willzangina/prj-rev-bwfs-tea-cozy/blob/003451c6007db9ffad3eb68f526f66874fd05205/Tea%20Cozy/index.html#L5

It looks like your styling isn't showing up! Remember that HTML is case sensitive, so you need to pay attention to your casing when you link files. Your resources file is capitalized, so this should be:

`<link rel="stylesheet" href="./Resources/style.css" type="text/css" />`

This is super important, because without proper casing, no one can see your styling! Check out how it shows up to me here: https://htmlpreview.github.io/?https://github.com/willzangina/prj-rev-bwfs-tea-cozy/blob/master/Tea%20Cozy/index.html

**Comment by willzangina** [comment]
Thanks; will take note for the future
