### ISSUE TITLE
HTML indentation

### ISSUE THREAD

**Issue by Rodrigap** [willzangina/prj-rev-bwfs-tea-cozy#2]
https://github.com/willzangina/prj-rev-bwfs-tea-cozy/blob/003451c6007db9ffad3eb68f526f66874fd05205/Tea%20Cozy/index.html#L57-L82

some of your HTML indentation is well done, but you don't always properly indent divs within other divs. Remember that every single child of another element needs to be indented and remain that way for the whole HTML file. So for example, you should never have multiple closing div tags in a row on the same level of indentation. For reference, here's how this code snippet should be indented:

```
<div class="locations">
  <span class="title">Locations</span>
  <div class="addresses">
    <div class="downtown">
      <span><h3>Downtown</h3>
      <p>384 West 4th St</p>
      <p>Suite 108</p>
      <p>Portland, Maine</p></span>
    </div>
    <div class="east-bayside">
      <span><h3>East Bayside</h3>
        <p>3433 Phisherman's Avenue</p>
        <p>(Northwest Corner)</p>
        <p>Portland, Maine</p></span>
      </div>
      <div class="oakdale">
        <span><h3>Oakdale</h3>
        <p>515 Cresent Avenue</p>
        <p>Second Floor</p>
        <p>Portland, Maine</p></span>
      </div>
    </div>
  </div>
</div>
```

**Comment by willzangina** [comment]
Great; thanks for reminding me. I shall pay attention on indentation next time.
