### ISSUE TITLE
CSS organization

### ISSUE THREAD

**Issue by Rodrigap** [willzangina/prj-rev-bwfs-tea-cozy#4]
https://github.com/willzangina/prj-rev-bwfs-tea-cozy/blob/003451c6007db9ffad3eb68f526f66874fd05205/Tea%20Cozy/Resources/style.css#L23-L34

Your CSS looks great, I love that you added comments here just like in your HTML! I'd recommend adding a single layer of blank space between each CSS object to spread out your code a bit and make it easier to read, like this:

```
}

.header nav {
  display: inline-block;
  padding: 20px 10px;
}

.header a {
  color: white;
  padding: 10px;
}

/*mission background*/

.main {
  display: flex;
```

**Comment by willzangina** [comment]
your comments are well appreciated. I shall work on the linking issue
