### ISSUE TITLE
Grade: Needs Improvement

### ISSUE THREAD

**Issue by Rodrigap** [willzangina/prj-rev-bwfs-tea-cozy#5]
This is a really good start to your project! Your HTML and CSS are both very functional. My biggest critique is that you didn't properly link your CSS file, so your HTML shows up completely unstyled. It's super important to get this right because you want everyone to see all your hard work! Besides that, I'd recommend cleaning up your HTML indentation a little bit. Some parts aren't properly indented, which makes it harder to read and understand. Other than that, it looks like you used all the proper HTML element tags, and I really appreciate that you used comments in both your HTML and CSS! Your CSS looks great, I just had one small suggestion about line breaks. Overall, I can tell you put a lot of time and effort into this, really nice job!

**Comment by willzangina** [comment]
comments very much appreciated. I didn't realize that my css file wasn't linking to my html file. On my pc the link appeared functional but obviously it wasn't when viewed externally. I should bear that in mind next time.

**Comment by willzangina** [comment]
well noted
